---
development:
  cloud_name: lessondb
  api_key: <%= ENV["cloudr_api_key"] %>
  api_secret: <%= ENV["cloudr_api_secret"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: lessondb
  api_key: <%= ENV["cloudr_api_key"] %>
  api_secret: <%= ENV["cloudr_api_secret"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: lessondb
  api_key: <%= ENV["cloudr_api_key"] %>
  api_secret: <%= ENV["cloudr_api_secret"] %>
  enhance_image_tag: true
  static_image_support: false
